-- Retrieve the top 10 highest-grossing movies along with their revenue.
SELECT m.title, r.revenue
FROM movies m
INNER JOIN revenue r ON m.movie_id = r.movie_id
ORDER BY r.revenue DESC
LIMIT 10;

-- Calculate the total revenue generated by all the movies in the database.
SELECT SUM(revenue) AS total_revenue
FROM revenue;

-- List the movies that have generated revenue greater than $1 million.

SELECT m.title, r.revenue
FROM movies m
INNER JOIN revenue r ON m.movie_id = r.movie_id
WHERE r.revenue > 1000000;

-- Find the average revenue generated by movies released in each year.

SELECT YEAR(m.release_date) AS release_year, AVG(r.revenue) AS avg_revenue
FROM movies m
INNER JOIN revenue r ON m.movie_id = r.movie_id
GROUP BY release_year;

-- Retrieve the movie titles along with their corresponding directors and total revenue.

SELECT m.title, m.director, SUM(r.revenue) AS total_revenue
FROM movies m
INNER JOIN revenue r ON m.movie_id = r.movie_id
GROUP BY m.title, m.director;




